### ISSUE TITLE
Noisy diff on logzio_alert_v2 when using multiple severity_threshold_tiers

### ISSUE THREAD

**Issue by andruwm** [logzio/terraform-provider-logzio#89]
This isn't a breaking issue, the alert's still get created as expected and work great. The terraform provider seems to compute the state for the thresholds in random order. My random stab of a guess is that this occurs because the provider is implemented in Go and Go map iteration order is random. The result is that the provider always thinks there was a change when nothing actually changed.

Terraform version: v0.15.4
Provider version: v1.3.0

Terraform resource:
```terraform
resource logzio_alert_v2 alert_service_errors {
  title                        = "${local.service_name}-service-errors-${terraform.workspace}"
  tags                         = local.tags_array
  is_enabled                   = true
  output_type                  = "JSON"
  alert_notification_endpoints = [
    data.terraform_remote_state.monitoring.outputs.logzio_slack_alerts_endpoint_id
  ]

  notification_emails = []

  description = <<-EOT
    Increase in application errors detected for the ${local.service_name} service.
    Created by Terraform: DO NOT EDIT.
  EOT

  search_timeframe_minutes       = 10
  suppress_notifications_minutes = 60
  joins                          = []

  sub_components {
    query_string                 = "service:\"${local.service_name}\" AND env:\"${local.env_name}\" AND level:\"error\""
    should_query_on_all_accounts = true
    operation                    = "GREATER_THAN_OR_EQUALS"
    value_aggregation_type       = "COUNT"
    group_by_aggregation_fields  = [
      "msg"
    ]
    account_ids_to_query_on      = []
    filter_must                  = []
    filter_must_not              = []

    dynamic severity_threshold_tiers {
      for_each = local.error_alert_thresholds[terraform.workspace]
      content {
        severity  = severity_threshold_tiers.value.severity
        threshold = severity_threshold_tiers.value.threshold
      }
    }
  }
}
```

Outputs:
```Note: Objects have changed outside of Terraform

Terraform detected the following changes made outside of Terraform since the last "terraform apply":

  # logzio_alert_v2.alert_service_errors has been changed
  ~ resource "logzio_alert_v2" "alert_service_errors" {
        id                             = "xxxxxx"
        tags                           = [
            "xxxxxxxx",
            "xxxxxxxx",
            "terraform",
        ]
        # (14 unchanged attributes hidden)

      ~ sub_components {
            # (8 unchanged attributes hidden)

          ~ severity_threshold_tiers {
              ~ severity  = "HIGH" -> "LOW"
              ~ threshold = 10 -> 2
            }
          ~ severity_threshold_tiers {
              ~ severity  = "LOW" -> "MEDIUM"
              ~ threshold = 2 -> 5
            }
          ~ severity_threshold_tiers {
              ~ severity  = "MEDIUM" -> "SEVERE"
              ~ threshold = 5 -> 100
            }
          ~ severity_threshold_tiers {
              ~ severity  = "SEVERE" -> "HIGH"
              ~ threshold = 100 -> 10
            }
        }
    }

Unless you have made equivalent changes to your configuration, or ignored the relevant attributes using ignore_changes, the following plan may include actions to undo or respond to these changes.

────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:


  # logzio_alert_v2.alert_service_errors will be updated in-place
  ~ resource "logzio_alert_v2" "alert_service_errors" {
        id                             = "xxxxxx"
        tags                           = [
            "xxxxxxx",
            "xxxxxxx",
            "terraform",
        ]
        # (14 unchanged attributes hidden)

      ~ sub_components {
            # (8 unchanged attributes hidden)

          ~ severity_threshold_tiers {
              ~ severity  = "LOW" -> "HIGH"
              ~ threshold = 2 -> 10
            }
          ~ severity_threshold_tiers {
              ~ severity  = "MEDIUM" -> "LOW"
              ~ threshold = 5 -> 2
            }
          ~ severity_threshold_tiers {
              ~ severity  = "SEVERE" -> "MEDIUM"
              ~ threshold = 100 -> 5
            }
          ~ severity_threshold_tiers {
              ~ severity  = "HIGH" -> "SEVERE"
              ~ threshold = 10 -> 100
            }
        }
    }

Plan: 0 to add, 2 to change, 0 to destroy.
```

**Comment by mirii1994** [comment]
Hi @andruwm thank you for informing us about this issue.
We'll look into it further and try to fix this :)

**Comment by mirii1994** [comment]
Hi @andruwm , v1.7.0 is out, and should fix this issue. Please let us know if this solves it for you :)

**Comment by andruwm** [comment]
I upgraded to v1.7.0, and attempted to run the same resource as above. I know get the following error
```bash
╷
│ Error: string is required
│
│   with logzio_alert_v2.alert_service_errors,
│   on logzio.tf line 19, in resource "logzio_alert_v2" "alert_service_errors":
│   19:   sub_components {
│
╵
```

I have not made any changes aside from updating the provider version.

**Comment by mirii1994** [comment]
We've made some changes in v1.5, and changed fields `filter_must` and `filter_must_not` from array to a json encoded string.
Try changing to this:
```
    filter_must = ""
    filter_must_not = ""
```

**Comment by andruwm** [comment]
Here is an updated TF resource that is still getting the same error
```terraform
resource logzio_alert_v2 alert_service_errors {
  title                        = "${local.service_name}-service-errors-${terraform.workspace}"
  tags                         = local.tags_array
  is_enabled                   = true
  output_type                  = "JSON"
  alert_notification_endpoints = [
    data.terraform_remote_state.monitoring.outputs.logzio_slack_alerts_endpoint_id
  ]

  notification_emails = []

  description = <<-EOT
    Increase in application errors detected for the ${local.service_name} service.
    Created by Terraform: DO NOT EDIT.
  EOT

  search_timeframe_minutes       = 10
  suppress_notifications_minutes = 60

  sub_components {
    query_string                 = "service:\"${local.service_name}\" AND env:\"${local.env_name}\" AND level:\"error\""
    should_query_on_all_accounts = true
    operation                    = "GREATER_THAN_OR_EQUALS"
    value_aggregation_type       = "COUNT"
    group_by_aggregation_fields  = [
      "msg"
    ]

    severity_threshold_tiers {
      severity  = "INFO"
      threshold = 5
    }
  }
}
```

**Comment by mirii1994** [comment]
Hi @andruwm ,
I tried using your configuration, just changed your `local.` & `terraform.` variables to strings, and it worked for me (tested with terraform 0.15.4, and logzio provider 1.7):

```hcl
terraform {
  required_providers {
    logzio = {
      source = "logzio/logzio"
      version = "1.7.0"
    }
  }
}

resource logzio_alert_v2 alert_service_errors {
  title                        = "hello"
  tags                         = ["some", "tags"]
  is_enabled                   = true
  output_type                  = "JSON"
  alert_notification_endpoints = []

  notification_emails = []

  description = <<-EOT
    Increase in application errors detected for the something service.
    Created by Terraform: DO NOT EDIT.
  EOT

  search_timeframe_minutes       = 10
  suppress_notifications_minutes = 60

  sub_components {
    query_string                 = "service:\"something\" AND env:\"something\" AND level:\"error\""
    should_query_on_all_accounts = true
    operation                    = "GREATER_THAN_OR_EQUALS"
    value_aggregation_type       = "COUNT"
    group_by_aggregation_fields  = [
      "msg"
    ]

    severity_threshold_tiers {
      severity  = "INFO"
      threshold = 5
    }
  }
}
```

Can you try & check this one out, to rule out the possibility that the issue is with those variables?

**Comment by mirii1994** [comment]
Hi @andruwm , was the issue resolved?

**Comment by andruwm** [comment]
Apologies for not responding more quickly! This issue is resolved!

**Comment by mirii1994** [comment]
Awesome!
